name: Build and Push Docker image to Docker Hub

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image
        run: docker build -t aalok013/stable_diffusion_runpod:latest --progress=plain .
      
      - name: Push Docker image
        run: docker push aalok013/stable_diffusion_runpod:latest
